---
title: "coinbaseR.rmd"
output: html_document
---

```{r}
library(httr)
library(RCurl)
library(digest)
library(stringr)
library(lubridate)
```


#####################

#API setup
```{r}
setup <- read.csv('setup.cfg')
settings <- setup$setting
values <- setup$value
setup <- data.frame(t(values))
colnames(setup) <- settings
s <- setup

print(s)
```

# IMPLEMETED FUNCTIONS
```{r}
account()
account('ETH')

account.hist()
account.hist('BTC')
account.hist("account ID HERE")

profile()
profile("Profile ID HERE")

products()
products('BTC-GBP')
products('BTC/GBP')

ticker()
ticker('BTC-GBP')

ticker.record(ID = 'btc-gbp', duration = '01:00:00', ticks.per.sec = 1)

historic('BTC-GBP')
historic('BTC-GBP', '2021-02-03 00:00:00', '2020-02-04 00:00:00')
```


# LIST ACCOUNTS
```{r}
account <- function(currency=NA){
  req.url <- "/accounts"
  method <- "GET"
  timestamp <- format(as.numeric(Sys.time()), digits=13)
  key <- base64Decode(s$secret, mode="raw")
  what <- paste0(timestamp, toupper(method), req.url)
  sign <- base64Encode(hmac(key, what, algo="sha256", raw=TRUE))
  
  r<- GET(url = paste0(s$api.url, req.url),
      add_headers(`CB-ACCESS-KEY`= s$api.key,
                  `CB-ACCESS-SIGN`=sign,
                  `CB-ACCESS-TIMESTAMP`= timestamp,
                  `CB-ACCESS-PASSPHRASE`=s$passphrase,
                  `Content-Type`='application/json'))
  c <- content(r)
  
  df <- data.frame(matrix(unlist(c), nrow=length(c), byrow=T))
  colnames(df) <- (names(c[[1]]))
  
  if(is.na(currency)){
    return(df)
  }else{
    return(df[df[2] == currency,])  
  }
}
```

# List Profiles (portfolios)
```{r}
profile <- function(ID=NA){
  ID <- str_r
  req.url <- "/profiles"
  method <- "GET"
  timestamp <- format(as.numeric(Sys.time()), digits=13)
  key <- base64Decode(s$secret, mode="raw")
  what <- paste0(timestamp, toupper(method), req.url)
  sign <- base64Encode(hmac(key, what, algo="sha256", raw=TRUE))
  
  r<- GET(url = paste0(s$api.url, req.url),
      add_headers(`CB-ACCESS-KEY`= s$api.key,
                  `CB-ACCESS-SIGN`=sign,
                  `CB-ACCESS-TIMESTAMP`= timestamp,
                  `CB-ACCESS-PASSPHRASE`=s$passphrase,
                  `Content-Type`='application/json'))
  c <- content(r)
  
  df <- data.frame(matrix(unlist(c), nrow=length(c), byrow=T))
  colnames(df) <- (names(c[[1]]))
  
  if(is.na(ID)){
    return(df)
  }else{
    return(df[df[1] == ID,])  
  }
}
```


# GET ACCOUNT HISTORY
```{r}
account.hist <- function(ID = NA) {
  if ((is.na(ID) == FALSE) && nchar(ID) < 5) {
    ID <- account(ID)[1]
  } else{
    ID <- ID
  }
  
  req.url <- paste0("/accounts/", ID, "/ledger")
  method <- "GET"
  timestamp <- format(as.numeric(Sys.time()), digits = 13)
  key <- base64Decode(s$secret, mode = "raw")
  what <- paste0(timestamp, toupper(method), req.url)
  sign <- base64Encode(hmac(key, what, algo = "sha256", raw = TRUE))
  
  r <- GET(
    url = paste0(s$api.url, req.url),
    add_headers(
      `CB-ACCESS-KEY` = s$api.key,
      `CB-ACCESS-SIGN` = sign,
      `CB-ACCESS-TIMESTAMP` = timestamp,
      `CB-ACCESS-PASSPHRASE` = s$passphrase,
      `Content-Type` = 'application/json'
    )
  )
  c <- content(r)
  
  df <- data.frame(matrix(unlist(c), nrow = length(c), byrow = T))
  colnames(df) <- (names(c[[1]]))
  
  if (is.na(ID)) {
    return("Must supply account ID or currency e.g. 'BTC', found using account() function.")
  } else{
    return(df)
  }
}
```


# Market Data -- Get products
```{r}
products <- function(ID = NA){
  ID <- str_replace(ID, "/", "-")
  req.url <- "/products"
  method <- "GET"
  timestamp <- format(as.numeric(Sys.time()), digits=13)
  key <- base64Decode(s$secret, mode="raw")
  what <- paste0(timestamp, toupper(method), req.url)
  sign <- base64Encode(hmac(key, what, algo="sha256", raw=TRUE))
  
  r<- GET(url = paste0(s$api.url, req.url),
      add_headers(`CB-ACCESS-KEY`= s$api.key,
                  `CB-ACCESS-SIGN`=sign,
                  `CB-ACCESS-TIMESTAMP`= timestamp,
                  `CB-ACCESS-PASSPHRASE`=s$passphrase,
                  `Content-Type`='application/json'))
  c <- content(r)
  
  
  df <- data.frame(matrix(unlist(c), nrow=length(c), byrow=T))
  colnames(df) <- (names(c[[1]]))

  if(is.na(ID)){
    return(df)
  }else{
    return(df[df[1] == ID,]) 
  }  
}

products('BTC/GBP')

```

# Product ticker
```{r}
ticker <- function(ID = NA){
  ID <- str_replace(ID, "/", "-")
  req.url <- paste0("/products/", ID, "/ticker")
  method <- "GET"
  timestamp <- format(as.numeric(Sys.time()), digits=13)
  key <- base64Decode(s$secret, mode="raw")
  what <- paste0(timestamp, toupper(method), req.url)
  sign <- base64Encode(hmac(key, what, algo="sha256", raw=TRUE))
  
  r<- GET(url = paste0(s$api.url, req.url),
      add_headers(`CB-ACCESS-KEY`= s$api.key,
                  `CB-ACCESS-SIGN`=sign,
                  `CB-ACCESS-TIMESTAMP`= timestamp,
                  `CB-ACCESS-PASSPHRASE`=s$passphrase,
                  `Content-Type`='application/json'))
  c <- content(r)
  
  df <- data.frame(matrix(unlist(c), ncol=length(c), byrow=F))
  colnames(df) <- c(names(c))
                    
  if(is.na(ID)){
    return("Must supply currency-pair e.g. 'BTC-GBP'.")
  }else{
    df <- cbind(ID, df)
    return(df) 
  }               
}


ticker('BTC-USD')
```

# ticker record
```{r}
ticker('btc-gbp')


ticker.record <- function(ID=NA, duration=NA, ticks.per.sec=1){
  startdatetime <<- Sys.time()
  runs <<- period_to_seconds(hms(duration))*ticks.per.sec
  df <<- data.frame(ticker(ID=ID))
  for(i in 1:runs){
    tick.data <<- data.frame(ticker(ID=ID))
    df[i,] <<- c(tick.data)
    #message(tick.data)
    message(paste0("[",Sys.time(),"] [", toupper(ID), "] [Current bid price is ", tick.data$bid, ", current ask is ", tick.data$ask, "]"))
    Sys.sleep(1/ticks.per.sec)
  }
  write.csv(df, paste0("recorded_data/one_offs/[", str_replace_all(str_replace_all(Sys.time(), ":", "-"), " ", "]___["), "]___data.csv"))
}



ticker.record(ID = 'btc-gbp', duration = "00:01:00", ticks.per.sec = 1)



```




# HISTORIC DATA
```{r}
historic <-
  function(ID = NA,
           start = Sys.time() - 43200,
           end = Sys.time(),
           granularity = 300) {
    start <- strftime(start, "%Y-%m-%dT%H:%M:%SZ", tz = system.timezone)
    end <- strftime(end, "%Y-%m-%dT%H:%M:%SZ", tz = system.timezone)
    ID <- str_replace(ID, "/", "-")
    req.url <- paste0("/products/", ID, "/candles")
    param.url <-
      URLencode(paste0("?start=", start, "&end=", end, "&granularity=", granularity),
                reserved = FALSE)
    method <- "GET"
    timestamp <- format(as.numeric(Sys.time()), digits = 13)
    key <- base64Decode(secret, mode = "raw")
    what <- paste0(timestamp, toupper(method), req.url, param.url)
    sign <- base64Encode(hmac(key, what, algo = "sha256", raw = TRUE))
    r <- GET(
      url = paste0(s$api.url, req.url, param.url),
      add_headers(
        `CB-ACCESS-KEY` = s$api.key,
        `CB-ACCESS-SIGN` = sign,
        `CB-ACCESS-TIMESTAMP` = timestamp,
        `CB-ACCESS-PASSPHRASE` = s$passphrase,
        `Content-Type` = 'application/json'
      )
    ) # ONE DAY
    c <- content(r)
    df <- data.frame(matrix(unlist(c), ncol = 6, byrow = T))
    if (is.na(ID)) {
      return("Must supply currency-pair e.g. 'BTC-GBP'.")
    } else{
      colnames(df) <- c('time', 'low', 'high', 'open', 'close', 'volume')
      df <- cbind(ID, df)
      df$time <- as.POSIXct(as.integer(df$time), origin = "1970-01-01")
      return(df)
      #return(c)
    }
  }

```